#define JM_COT

//#define JM_COT_LOGGING

//#define JM_COT_ESP_DEBUG

//#define JM_COT_WEBHOOK_DEBUG

#define JM_COT_VEHICLE_ONSPAWNVEHICLE

#define COT_BUGFIX_REF

#ifndef CF_DOUBLYLINKEDNODES
#ifndef EXPANSION_DOUBLYLINKEDNODES
#define JM_COT_DOUBLYLINKEDNODES
#endif
#endif
