#define JM_COT

//#define JM_COT_LOGGING

//#ifdef DIAG
////#define JM_COT_DIAG_LOGGING
//#endif

//#define JM_COT_ESP_DEBUG

//#define JM_COT_WEBHOOK_DEBUG

#define JM_COT_VEHICLE_ONSPAWNVEHICLE

#define COT_BUGFIX_REF

#define JM_COT_VEHICLEMANAGER
#define JM_COT_INVISIBILITY

#ifndef CF_DOUBLYLINKEDNODES
#ifndef EXPANSION_DOUBLYLINKEDNODES
#define JM_COT_DOUBLYLINKEDNODES
#endif
#endif

#define JM_COT_EXPTRANSITION_1