#define JM_COT

//#define JM_COT_LOGGING

//#ifdef DIAG
//#define JM_COT_DIAG_LOGGING
//#endif

//#define JM_COT_ESP_DEBUG

//#define JM_COT_WEBHOOK_DEBUG

#define JM_COT_VEHICLE_ONSPAWNVEHICLE

#define COT_BUGFIX_REF
#define COT_BUGFIX_REF_UIACTIONS
#define COT_UIACTIONS_SETWIDTH
#define COT_REFRESHSTATS_NEW

#define JM_COT_VEHICLEMANAGER
#define JM_COT_INVISIBILITY

#ifndef CF_DOUBLYLINKEDNODES
#ifndef EXPANSION_DOUBLYLINKEDNODES
#ifndef EXPANSION_DOUBLYLINKEDNODES_WEAKREF
#define JM_COT_DOUBLYLINKEDNODES
#endif
#endif
#endif

#define JM_COT_EXPTRANSITION_1